import React from 'react'
import { Download, Globe2, KeyRound, Laptop, LockKeyhole, Plus, RefreshCw, Save, ShieldAlert, ShieldCheck, Trash2, UserRound } from 'lucide-react'
import { Link } from '../router'
import { getList, getOne, send } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { Alert, Button, Card, ConfirmDialog, EmptyState, Field, Modal, PageHeader, SkeletonRows, StatusBadge } from '../components/ui'
import { useAction, useApi } from '../hooks/useApi'
import type { UnknownRecord } from '../types'
import { formatDate } from '../utils/format'

interface LoginSession extends UnknownRecord { id: string; device?: string; browser?: string; location?: string; ipAddress?: string; lastActiveAt?: string; current?: boolean }
interface Destination extends UnknownRecord { id: string; name: string; hostname: string; allowedMethods?: string[]; status?: string; verifiedAt?: string }
interface DataRequest extends UnknownRecord { id: string; type: 'export' | 'closure'; status: string; downloadUrl?: string | null; requestedAt?: string; completedAt?: string; evidence?: UnknownRecord }
interface PlanPolicy extends UnknownRecord { plan?: string; maxConnections?: number; maxRetentionDays?: number; workflowVersionLimit?: number | null; workflowHistoryDays?: number }
interface SettingsData { organization: UnknownRecord; planPolicy: PlanPolicy; sessions: LoginSession[]; destinations: Destination[]; dataRequests: DataRequest[] }

async function loadSettings(): Promise<SettingsData> {
  const [organizationResult, sessionResult, destinationResult, dataRequestResult] = await Promise.allSettled([getOne<UnknownRecord>('/organizations/current'), getList<LoginSession>('/auth/sessions', ['sessions']), getList<Destination>('/connections/destinations', ['destinations']), getList<DataRequest>('/organizations/current/data-requests')])
  const outer = organizationResult.status === 'fulfilled' ? organizationResult.value : {}
  const organization = outer.organization && typeof outer.organization === 'object' && !Array.isArray(outer.organization) ? outer.organization as UnknownRecord : outer
  const planPolicy = outer.planPolicy && typeof outer.planPolicy === 'object' && !Array.isArray(outer.planPolicy) ? outer.planPolicy as PlanPolicy : {}
  const sessions = sessionResult.status === 'fulfilled' ? sessionResult.value.items.map((item) => ({
    ...item,
    device: String(item.device ?? item.browser ?? item.userAgent ?? 'Unknown device'),
    lastActiveAt: String(item.lastActiveAt ?? item.lastUsedAt ?? item.createdAt ?? ''),
  })) : []
  const destinations = destinationResult.status === 'fulfilled' ? destinationResult.value.items.map((item) => ({
    ...item,
    hostname: String(item.hostname ?? ''),
    allowedMethods: Array.isArray(item.allowedMethods) ? item.allowedMethods.map(String) : ['POST'],
    status: String(item.status ?? 'verified'),
  })) : []
  const dataRequests = dataRequestResult.status === 'fulfilled' ? dataRequestResult.value.items : []
  return { organization, planPolicy, sessions, destinations, dataRequests }
}

export default function SettingsPage() {
  const { session, updateUser, refresh } = useAuth()
  const query = useApi(loadSettings, [session?.organization?.id])
  const action = useAction()
  const [tab, setTab] = React.useState<'profile' | 'security' | 'workspace' | 'destinations' | 'privacy'>('profile')
  const [profile, setProfile] = React.useState({ name: session?.user.name ?? '', email: session?.user.email ?? '' })
  const [password, setPassword] = React.useState({ currentPassword: '', newPassword: '', confirm: '' })
  const [workspace, setWorkspace] = React.useState({ name: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, retentionDays: '7' })
  const [destinationOpen, setDestinationOpen] = React.useState(false)
  const [destination, setDestination] = React.useState({ name: '', exactUrl: '', allowedMethods: ['POST'] })
  const [revoke, setRevoke] = React.useState<LoginSession | null>(null)
  const [disableMfaOpen, setDisableMfaOpen] = React.useState(false)
  const [mfaDisable, setMfaDisable] = React.useState({ password: '', code: '' })
  const [closureOpen, setClosureOpen] = React.useState(false)
  const [closureConfirmation, setClosureConfirmation] = React.useState('')
  React.useEffect(() => { const org = query.data?.organization; if (org) setWorkspace({ name: String(org.name ?? session?.organization?.name ?? ''), timezone: String(org.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone), retentionDays: String(org.retentionDays ?? 7) }) }, [query.data, session?.organization?.name])

  const saveProfile = async (event: React.FormEvent) => { event.preventDefault(); const result = await action.run(() => send<UnknownRecord>('patch', '/auth/profile', { name: profile.name }), 'Profile updated.'); if (result) updateUser({ name: profile.name }) }
  const changePassword = async (event: React.FormEvent) => { event.preventDefault(); if (password.newPassword !== password.confirm) return; const result = await action.run(() => send('post', '/auth/change-password', { currentPassword: password.currentPassword, newPassword: password.newPassword }), 'Password updated and other sessions revoked.'); if (result !== undefined) setPassword({ currentPassword: '', newPassword: '', confirm: '' }) }
  const saveWorkspace = async (event: React.FormEvent) => { event.preventDefault(); await action.run(() => send('patch', '/organizations/current', { ...workspace, retentionDays: Number(workspace.retentionDays) }), 'Workspace settings saved.'); await refresh() }
  const revokeSession = async () => { if (!revoke) return; const done = await action.run(async () => { await send('delete', `/auth/sessions/${revoke.id}`); return true }, 'Session revoked.'); if (done) { setRevoke(null); await query.reload() } }
  const disableMfa = async (event: React.FormEvent) => { event.preventDefault(); const result = await action.run(() => send('delete', '/auth/mfa', mfaDisable), 'Multi-factor authentication disabled.'); if (result !== undefined) { setDisableMfaOpen(false); setMfaDisable({ password: '', code: '' }); await refresh() } }
  const addDestination = async (event: React.FormEvent) => { event.preventDefault(); const result = await action.run(() => send('post', '/connections/destinations', { ...destination, headers: {} }), 'Destination verified and approved.'); if (result !== undefined) { setDestinationOpen(false); setDestination({ name: '', exactUrl: '', allowedMethods: ['POST'] }); await query.reload() } }
  const removeDestination = async (id: string) => { await action.run(() => send('delete', `/connections/destinations/${id}`), 'Destination removed.'); await query.reload() }
  const requestExport = async () => { const result = await action.run(() => send('post', '/organizations/current/export', {}), 'Workspace export queued.'); if (result !== undefined) await query.reload() }
  const requestClosure = async (event: React.FormEvent) => { event.preventDefault(); if (closureConfirmation !== 'DELETE WORKSPACE') return; const result = await action.run(() => send('post', '/organizations/current/closure', { confirmation: closureConfirmation }), 'Verified workspace deletion queued.'); if (result !== undefined) { setClosureOpen(false); setClosureConfirmation(''); await query.reload() } }
  const canManage = ['owner', 'admin'].includes(session?.organization?.role ?? '')
  const isOwner = session?.organization?.role === 'owner'
  const maxRetentionDays = Number(query.data?.planPolicy.maxRetentionDays ?? 7)
  const retentionOptions = [7, 30, 90].filter((days) => days <= maxRetentionDays)

  return <>
    <PageHeader eyebrow="Account & workspace" title="Settings" description="Manage your identity, security controls and workspace policy." />
    {action.error && <Alert onDismiss={action.clear}>{action.error}</Alert>}{action.success && <Alert tone="success" onDismiss={action.clear}>{action.success}</Alert>}
    <div className="settings-layout"><nav className="settings-tabs" aria-label="Settings sections"><button className={tab === 'profile' ? 'active' : ''} onClick={() => setTab('profile')}><UserRound size={17} />Profile</button><button className={tab === 'security' ? 'active' : ''} onClick={() => setTab('security')}><ShieldCheck size={17} />Security</button>{canManage && <button className={tab === 'workspace' ? 'active' : ''} onClick={() => setTab('workspace')}><Globe2 size={17} />Workspace</button>}{canManage && <button className={tab === 'destinations' ? 'active' : ''} onClick={() => setTab('destinations')}><KeyRound size={17} />Destinations</button>}{canManage && <button className={tab === 'privacy' ? 'active' : ''} onClick={() => setTab('privacy')}><ShieldAlert size={17} />Data & privacy</button>}</nav><div className="settings-content">
      {tab === 'profile' && <Card title="Personal profile" subtitle="Used for invitations, approvals and audit history."><form className="settings-form" onSubmit={saveProfile}><Field label="Full name" required><input value={profile.name} onChange={(event) => setProfile((current) => ({ ...current, name: event.target.value }))} required /></Field><Field label="Email address" hint="Contact support to change the account email."><input type="email" value={profile.email} disabled /></Field><div><Button variant="primary" busy={action.loading}><Save size={16} />Save profile</Button></div></form></Card>}
      {tab === 'security' && <div className="stack"><Card title="Multi-factor authentication" subtitle="Require a second factor when signing in."><div className="setting-row"><div className="setting-icon"><ShieldCheck /></div><div><strong>Authenticator app</strong><p>{session?.user.mfaEnabled ? 'Enabled for your account.' : 'Not enabled. Owners and admins should enable MFA.'}</p></div><StatusBadge status={session?.user.mfaEnabled ? 'active' : 'attention'} /><div className="inline-actions"><Link className="button button-secondary button-sm" to="/mfa-setup">{session?.user.mfaEnabled ? 'Reset MFA' : 'Enable MFA'}</Link>{session?.user.mfaEnabled && <Button size="sm" variant="ghost" onClick={() => setDisableMfaOpen(true)}>Disable</Button>}</div></div></Card><Card title="Change password" subtitle="Changing your password revokes other active sessions."><form className="settings-form" onSubmit={changePassword}><Field label="Current password" required><input type="password" autoComplete="current-password" value={password.currentPassword} onChange={(event) => setPassword((current) => ({ ...current, currentPassword: event.target.value }))} required /></Field><div className="form-grid"><Field label="New password" required><input type="password" minLength={12} autoComplete="new-password" value={password.newPassword} onChange={(event) => setPassword((current) => ({ ...current, newPassword: event.target.value }))} required /></Field><Field label="Confirm password" error={password.confirm && password.confirm !== password.newPassword ? 'Passwords do not match.' : undefined} required><input type="password" minLength={12} autoComplete="new-password" value={password.confirm} onChange={(event) => setPassword((current) => ({ ...current, confirm: event.target.value }))} required /></Field></div><div><Button variant="primary" disabled={Boolean(password.confirm && password.confirm !== password.newPassword)} busy={action.loading}><LockKeyhole size={16} />Update password</Button></div></form></Card><Card title="Active sessions" subtitle="Review devices signed in to your account.">{query.loading ? <SkeletonRows rows={3} columns={3} /> : query.data?.sessions.length ? <div className="session-list">{query.data.sessions.map((item) => <div key={item.id}><span className="setting-icon"><Laptop /></span><div><strong>{item.device ?? item.browser ?? 'Unknown device'} {item.current && <StatusBadge status="active" label="This device" />}</strong><p>{item.location ?? item.ipAddress ?? 'Location unavailable'} · {formatDate(item.lastActiveAt)}</p></div>{!item.current && <Button size="sm" variant="ghost" onClick={() => setRevoke(item)}>Revoke</Button>}</div>)}</div> : <EmptyState title="No session details" description="Session telemetry will appear after your next sign-in." />}</Card></div>}
      {tab === 'workspace' && <Card title="Workspace policy" subtitle={`Applies to every member. The ${String(query.data?.planPolicy.plan ?? 'free')} plan allows up to ${maxRetentionDays} days of operational logs.`}><form className="settings-form" onSubmit={saveWorkspace}><Field label="Workspace name" required><input value={workspace.name} onChange={(event) => setWorkspace((current) => ({ ...current, name: event.target.value }))} required /></Field><div className="form-grid"><Field label="Default timezone" required><input value={workspace.timezone} onChange={(event) => setWorkspace((current) => ({ ...current, timezone: event.target.value }))} required /></Field><Field label="Execution retention"><select value={workspace.retentionDays} onChange={(event) => setWorkspace((current) => ({ ...current, retentionDays: event.target.value }))}>{retentionOptions.map((days) => <option value={days} key={days}>{days} days</option>)}</select></Field></div><div><Button variant="primary" busy={action.loading}><Save size={16} />Save policy</Button></div></form></Card>}
      {tab === 'destinations' && <Card title="Approved HTTP destinations" subtitle="Workflow nodes can send only to verified HTTPS hosts." actions={<Button size="sm" variant="primary" onClick={() => setDestinationOpen(true)}><Plus size={15} />Add destination</Button>}>{query.data?.destinations.length ? <div className="destination-list">{query.data.destinations.map((item) => <div key={item.id}><span className="setting-icon"><Globe2 /></span><div><strong>{item.name}</strong><p>{item.hostname} · {(item.allowedMethods ?? ['POST']).join(', ')}</p></div><StatusBadge status={item.status ?? 'verified'} />{item.status !== 'disabled' && <button className="icon-button danger-hover" onClick={() => { void removeDestination(item.id) }} aria-label={`Disable ${item.name}`}><Trash2 size={16} /></button>}</div>)}</div> : <EmptyState title="No approved destinations" description="Add a destination before using the approved webhook node." action={<Button onClick={() => setDestinationOpen(true)}><Plus size={15} />Add destination</Button>} />}</Card>}
      {tab === 'privacy' && <div className="stack"><Card title="Full workspace export" subtitle="Creates an encrypted, tenant-scoped NDJSON archive. The download expires after seven days." actions={<Button size="sm" onClick={() => { void query.reload() }}><RefreshCw size={15} />Refresh</Button>}><div className="setting-row"><div className="setting-icon"><Download /></div><div><strong>Portable data export</strong><p>Includes workspace configuration, operational records, usage and audit history. Credential ciphertext and authentication secrets are excluded.</p></div><Button variant="primary" busy={action.loading} onClick={() => { void requestExport() }}>Request export</Button></div>{query.data?.dataRequests.filter((item) => item.type === 'export').map((item) => <div className="setting-row" key={item.id}><div><strong>Export {formatDate(item.requestedAt)}</strong><p>Status: {item.status}{item.evidence?.expiresAt ? ` · expires ${formatDate(String(item.evidence.expiresAt))}` : ''}</p></div><StatusBadge status={item.status} />{item.downloadUrl && <a className="button button-secondary button-sm" href={item.downloadUrl}><Download size={15} />Download</a>}</div>)}</Card><Card title="Delete workspace" subtitle="Revokes provider credentials, deletes stored artifacts and tenant records, then issues a verifiable deletion certificate."><Alert tone="warning"><strong>This is irreversible.</strong> Export your data first. MFA and a sign-in from the last 15 minutes are required.</Alert><div className="setting-row"><div className="setting-icon"><Trash2 /></div><div><strong>Permanent verified deletion</strong><p>Your account remains available for other workspaces and for viewing the deletion certificate.</p></div><Button variant="danger" disabled={!isOwner || !session?.user.mfaEnabled} onClick={() => setClosureOpen(true)}>Delete workspace</Button></div>{!session?.user.mfaEnabled && <p>Enable MFA in Security before deleting a workspace.</p>}{query.data?.dataRequests.filter((item) => item.type === 'closure').map((item) => <div className="setting-row" key={item.id}><div><strong>Deletion request</strong><p>{item.status} · {item.evidence?.certificateHash ? `certificate ${String(item.evidence.certificateHash).slice(0, 16)}…` : 'credential revocation and purge evidence pending'}</p></div><StatusBadge status={item.status} /></div>)}</Card></div>}
    </div></div>
    <Modal open={destinationOpen} title="Add approved destination" description="Private, loopback and cloud metadata addresses are always blocked." onClose={() => setDestinationOpen(false)} footer={<><Button onClick={() => setDestinationOpen(false)}>Cancel</Button><Button variant="primary" form="destination-form" type="submit" busy={action.loading}>Verify destination</Button></>}><form id="destination-form" className="form-stack" onSubmit={addDestination}><Field label="Display name" required><input value={destination.name} onChange={(event) => setDestination((current) => ({ ...current, name: event.target.value }))} required autoFocus /></Field><Field label="Exact HTTPS URL" hint="Requests are restricted to this verified URL and the selected methods." required><input type="url" pattern="https://.*" value={destination.exactUrl} onChange={(event) => setDestination((current) => ({ ...current, exactUrl: event.target.value }))} placeholder="https://api.example.com/hooks" required /></Field><Field label="Allowed method"><select value={destination.allowedMethods[0]} onChange={(event) => setDestination((current) => ({ ...current, allowedMethods: [event.target.value] }))}><option value="POST">POST</option><option value="PUT">PUT</option><option value="PATCH">PATCH</option><option value="GET">GET</option></select></Field></form></Modal>
    <Modal open={disableMfaOpen} title="Disable multi-factor authentication?" description="Confirm your password and a current authenticator code. This reduces account protection." onClose={() => setDisableMfaOpen(false)} footer={<><Button onClick={() => setDisableMfaOpen(false)}>Cancel</Button><Button variant="danger" form="disable-mfa-form" type="submit" busy={action.loading}>Disable MFA</Button></>}><form id="disable-mfa-form" className="form-stack" onSubmit={disableMfa}><Field label="Current password" required><input type="password" autoComplete="current-password" value={mfaDisable.password} onChange={(event) => setMfaDisable((current) => ({ ...current, password: event.target.value }))} required autoFocus /></Field><Field label="Six-digit authenticator code" required><input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={mfaDisable.code} onChange={(event) => setMfaDisable((current) => ({ ...current, code: event.target.value.replace(/\D/g, '') }))} required /></Field></form></Modal>
    <Modal open={closureOpen} title="Permanently delete this workspace?" description="Provider access is blocked first. LogicFlower then verifies credential deletion, removes tenant data and preserves only a deletion certificate." onClose={() => setClosureOpen(false)} footer={<><Button onClick={() => setClosureOpen(false)}>Cancel</Button><Button variant="danger" form="closure-form" type="submit" busy={action.loading} disabled={closureConfirmation !== 'DELETE WORKSPACE'}>Queue verified deletion</Button></>}><form id="closure-form" className="form-stack" onSubmit={requestClosure}><Alert tone="warning">This cannot be undone. Type <strong>DELETE WORKSPACE</strong> exactly.</Alert><Field label="Confirmation" required><input value={closureConfirmation} onChange={(event) => setClosureConfirmation(event.target.value)} autoComplete="off" placeholder="DELETE WORKSPACE" required autoFocus /></Field></form></Modal>
    <ConfirmDialog open={Boolean(revoke)} title="Revoke this session?" description="That device will be signed out immediately and must authenticate again." confirmLabel="Revoke session" danger busy={action.loading} onClose={() => setRevoke(null)} onConfirm={() => { void revokeSession() }} />
  </>
}
